### ISSUE TITLE
Cannot deploy blockchain to testnet sepolia

### ISSUE THREAD

**Issue by vthuan-dev** [vthuan-dev/Blockchain-Traceability#9]
PS D:\projects\nckh-be\blockchain> truffle migrate --network sepolia --reset
>> 
MNEMONIC from env: witch collapse practice feed shame open despair creek road again ice 
least
MNEMONIC length: 12
INFURA_PROJECT_ID: 70a7bf700e4d43d99416d55c6b557d3b

Compiling your contracts...
===========================
> Compiling .\contracts\ActivityLog.sol
> Compiling .\contracts\supplychain.sol
> Artifacts written to D:\projects\nckh-be\blockchain\build\contracts
> Compiled successfully using:
   - solc: 0.8.20+commit.a1b79de6.Emscripten.clang
Error: Mnemonic invalid or undefined
    at HDWalletProvider.checkBIP39Mnemonic (D:\projects\nckh-be\node_modules\@truffle\hdwallet-provider\src\index.ts:325:13)        
    at new HDWalletProvider (D:\projects\nckh-be\node_modules\@truffle\hdwallet-provider\src\index.ts:109:12)
    at Object.provider (D:\projects\nckh-be\blockchain\truffle-config.js:15:23)
    at Object.getProvider (C:\Users\Admin\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\provider\index.js:20:1)  
    at Object.create (C:\Users\Admin\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\provider\index.js:13:1)       
    at TruffleConfig.get [as provider] (C:\Users\Admin\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\config\dist\configDefaults.js:276:1)
    at Object.detect (C:\Users\Admin\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\environment\environment.js:19:1)
    at Object.module.exports [as run] (C:\Users\Admin\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\commands\migrate\run.js:19:1)
    at runCommand (C:\Users\Admin\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\command-utils.js:297:1) 
Truffle v5.11.5 (core: 5.11.5)
Node v20.16.0

**Comment by LocNguyen-807** [comment]
Can you assign me, sir. I won't make you disappoint, I have 30 years of experiment in this field

**Comment by vthuan-dev** [comment]
gke z shao
